### PR TITLE
epds udated, education postnatal added, wrong anxiety variables corrected

### PR DESCRIPTION
**Pull request by SereDef**

### CODE REVIEW

**Review by VilteBaltra — COMMENTED** [review]
I can see you changed the anxiety items back to mode. I just corrected them yesterday into 'complete' instead of 'mode'. I thought we had agrred to use the 'complete' items. Or did you now decide to go back to using mode imputed ones?

**Comment by SereDef** [comment]
> I can see you changed the anxiety items back to mode. I just corrected them yesterday into 'complete' instead of 'mode'. I thought we had agrred to use the 'complete' items. Or did you now decide to go back to using mode imputed ones?

Yes, I ran the scripts with Tom and I think there was a misunderstanding on what variables to use. Now I understand the correct variable is the first one, correct? In that case I also changed b371 to b370 and c601 to c600. Correct? We also found some errors in the anxiety variables (e.g. b351 = Crown Crisp - Anxiety, changed to b352a anxiety subscale of CCEI in HAB). So one final time, could you have a look to see if these psychopathology variables are the correct ones? 

We also noticed the mistake in the epds function and corrected it.

**Comment by VilteBaltra** [comment]
I wouldn't change b371 to b370 and c601 to c600 because they are dichotomous already. I included a calculation of the total score for them instead (see the commit from yesterday). I also noted this in the email I sent yesterday.

**Comment by VilteBaltra** [comment]
The b351 variable was the correct one.. b352a is the mode-imputed one

**Comment by SereDef** [comment]
No i am sorry i don't think so, Crown Crisp is a different scale
[image: Screenshot 2021-07-21 at 10.43.52.png]


Il giorno mer 21 lug 2021 alle ore 10:39 VilteB ***@***.***>
ha scritto:

**Comment by VilteBaltra** [comment]
I can't see the image you attached but in ALSPAC documentation the two variables are defined as:  

B351 Crown Crisp - Anxiety = d1 + d9 + d15 + d17 + d3 + d6 + d12 + d20 provided all 8 values were valid (otherwise put to -1)

B352A Anxiety subscale of CCEI in HAB = d1 + d9 + d15 + d17 + d3 + d6 + d12 +d20 putting missing values as the mode. If all 8 variables values were missing then B352A was coded as -1. 

As you can see, both variables consist of identical items, with the only difference being that b351 uses complete values, whereas b352a mode-imputed.

**Comment by SereDef** [comment]
Oh i see, thank you, sorry for the hustle,  I will fix it back to the
correct one :)

Il giorno mer 21 lug 2021 alle ore 10:49 VilteB ***@***.***>
ha scritto:

**Pull request merged**
